apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: next-me
  labels:
    app: user-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: user-service
          image: ghcr.io/sparta-next-me/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12000

          envFrom:
            - secretRef:
                name: user-service-env

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            # [추가] 자바 프로세스가 사용할 메모리 범위를 명시적으로 지정
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx768m"

          # [수정] 앱이 뜨는 시간이 40초 정도 걸리므로 지연 시간을 늘림
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 12000
            initialDelaySeconds: 60 # 30초에서 60초로 변경
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 12000
            initialDelaySeconds: 90 # 60초에서 90초로 변경
            periodSeconds: 20

          # [수정] 메모리 한계치를 상향 조정 (핵심!)
          resources:
            requests:
              cpu: "200m"      # 100m에서 약간 상향
              memory: "512Mi"  # 256Mi에서 상향
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: next-me
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 12000
      targetPort: 12000
  type: ClusterIP