apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: next-me
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: user-service
          image: ghcr.io/sparta-next-me/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12000

          # Secret에 있는 환경변수 전부 가져오기
          envFrom:
            - secretRef:
                name: user-service-env

          # 추가로, 우리가 직접 지정할 env (프로필)
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: next-me
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 12000
      targetPort: 12000
  type: ClusterIP
